[phases.setup]
nixPkgs = ["ffmpeg"]
aptPkgs = [
  "libnss3",
  "libdbus-1-3",
  "libatk1.0-0",
  "libgbm-dev",
  "libasound2",
  "libxrandr2",
  "libxkbcommon-dev",
  "libxfixes3",
  "libxcomposite1",
  "libxdamage1",
  "libatk-bridge2.0-0",
  "libpango-1.0-0",
  "libcairo2",
  "libcups2",
  "fonts-noto-color-emoji",
  "fonts-noto-cjk"
]

[phases.install]
cmds = ['npm i -g pnpm && pnpm install']